
 // This code was generated by a tool. Any changes made manually will be lost
 // the next time this code is regenerated.
 // 
  
 #if KSP1_4
 using System.Reflection;

 [assembly: AssemblyVersion("1.4.6.0")]
 #endif